--Prob 1
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL
FROM A5_EMPLOYEEC
WHERE EMP_LNAME LIKE 'Smith%'

--Prob 2
SELECT P.PROJ_NAME, P.PROJ_VALUE, P.PROJ_BALANCE, E.EMP_LNAME, E.EMP_FNAME, E.EMP_INITIAL, J.A5_JOB_CODE, J.A5_JOB_DESCRIPTION, J.A5_JOB_CHG_HOUR
FROM A5_EMPLOYEEC E JOIN A5_PROJECT P
ON E.EMP_NUM = P.EMP_NUM
INNER JOIN A5_JOB J
ON J.A5_JOB_CODE =E.A5_JOB_CODE
ORDER BY PROJ_VALUE

--Prob 3
SELECT P.PROJ_NAME, P.PROJ_VALUE, P.PROJ_BALANCE, E.EMP_LNAME, E.EMP_FNAME, E.EMP_INITIAL, J.A5_JOB_CODE, J.A5_JOB_DESCRIPTION, J.A5_JOB_CHG_HOUR
FROM A5_EMPLOYEEC E JOIN A5_PROJECT P
ON E.EMP_NUM = P.EMP_NUM
INNER JOIN A5_JOB J
ON J.A5_JOB_CODE =E.A5_JOB_CODE
ORDER BY E.EMP_LNAME

--PROB 4
SELECT DISTINCT PROJ_NUM
FROM A5_PROJECT 
ORDER BY PROJ_NUM

--Prob 5
select ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, ASSIGN_CHG_HR*ASSIGN_HOURS 'TOTALCOST'
from A5_ASSIGNMENT
ORDER BY ASSIGN_NUM

--Prob 6
SELECT E.EMP_NUM, E.EMP_LNAME, SUM(ASSIGN_HOURS) 'SumOfASSIGN_HOURS', SUM(ASSIGN_HOURS)*ASSIGN_CHG_HR 'SumOfASSIGN_CHARGE'
FROM A5_ASSIGNMENT A JOIN A5_EMPLOYEEC E
ON A.EMP_NUM = E.EMP_NUM
GROUP BY E.EMP_NUM, E.EMP_LNAME
ORDER BY EMP_NUM

--Prob 7
SELECT P.PROJ_NUM, SUM(ASSIGN_HOURS) 'SumOfASSIGN_HOURS', SUM(ASSIGN_HOURS)*ASSIGN_CHG_HR 'SumOfASSIGN_CHARGE'
FROM A5_ASSIGNMENT A JOIN A5_PROJECT P
ON A.PROJ_NUM =P.PROJ_NUM
GROUP BY P.PROJ_NUM

--Prob 8
SELECT ROUND(SUM(SumOfASSIGN_HOURS),2) 'SumOfSumOfASSIGN_HOURS', ROUND(SUM(SumOfASSIGN_CHARGE), 2) 'SumOfSumOfASSIGN_CHARGE' FROM(
SELECT SUM(ASSIGN_HOURS) AS SumOfASSIGN_HOURS, SUM(ASSIGN_HOURS)*ASSIGN_CHG_HR AS SumOfASSIGN_CHARGE FROM A5_ASSIGNMENT GROUP BY ASSIGN_HOURS, ASSIGN_CHG_HR) db